# Generated by Django 3.1.1 on 2020-09-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='Fundacja Organizacja pozarządowa Zbiórka lokalna ',
        ),
        migrations.AddField(
            model_name='institution',
            name='type',
            field=models.IntegerField(choices=[(1, 'Fundacja'), (2, 'Organizacja pozarządowa'), (3, 'Zbiórka lokalna')], default=1),
        ),
    ]
