# Generated by Django 3.1.1 on 2020-09-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0003_auto_20200906_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.TextField(choices=[('fundacja', 'Fundacja'), ('organizacja', 'Organizacja pozarządowa'), ('zbiórka', 'Zbiórka lokalna')]),
        ),
    ]
