# Generated by Django 3.1.1 on 2020-09-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0007_auto_20200906_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.CharField(choices=[('FN', 'Fundacja'), ('OR', 'Organizacja pozarządowa'), ('CT', 'Zbiórka lokalna')], max_length=2),
        ),
    ]
