# Generated by Django 3.1.1 on 2020-09-14 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0009_auto_20200911_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='adress',
            new_name='address',
        ),
    ]
